#!/bin/bash
echo "========================================="
echo "QUICK GENERATE PAGE CHECK"
echo "========================================="
echo ""
echo "Opening https://repurpose-orpin.vercel.app/generate in your browser..."
echo ""
open "https://repurpose-orpin.vercel.app/generate"
echo ""
echo "Please check in your browser:"
echo ""
echo "✅ Do you see: '✓ 2 platform(s) connected: twitter, linkedin' ?"
echo "   - If YES: The fix worked!"
echo "   - If NO: Check what message you see"
echo ""
echo "❌ Do you see an error toast that says 'Could not load connected accounts' ?"
echo "   - If YES: The fix did NOT work"
echo "   - If NO: Good!"
echo ""
echo "📋 Copy and paste what you see on the page back to me"
echo ""
